- hosts: all
  name: Lenovo XClarity job
  tasks:
    - name: Find old files to delete
      find:
        paths: /tmp
        patterns: "*.log,*.service,ansible.*,rootwrap.*,tmp.*"
      register: files_to_delete

    - name: Remove old files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Remove old workspace
      file:
        path: '/tmp/xclarity'
        state: absent

    - name: Create workspace directory to run xclarity
      file:
        path: '/tmp/xclarity'
        state: directory

    - block:
        - name: Cloning Lenovo defined jobs for xclarity
          shell: |
            cd /tmp/xclarity
            git clone https://github.com/lenovo-lxca-ci/LENOVO-CI-JOBS.git

        - name: Configure molten
          shell: sudo bash /tmp/xclarity/LENOVO-CI-JOBS/molteniron/configure_molten.sh

        - name: Generate MoltenIron Id for node
          command: uuidgen
          register: uuid
 
        - name: Allocating test node
          shell: python /tmp/xclarity/LENOVO-CI-JOBS/molteniron/allocate_molten.py {{ uuid.stdout }} static-vms
 
        - name: Running xclarity gate
          shell: bash /tmp/xclarity/LENOVO-CI-JOBS/xclarity/gate.sh
    
      always:
        - name: Deallocating test node
          shell: python /tmp/xclarity/LENOVO-CI-JOBS/molteniron/release_molten.py {{ uuid.stdout }}
